#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py wait_for_db
python manage.py migrate
python manage.py collectstatic --no-input
python manage.py create_default_user
gunicorn --workers=1 butfit_backend_seunwoolee.wsgi:application --bind 0.0.0.0:8000