# Generated by Django 4.1.1 on 2022-10-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, verbose_name='정책명')),
                ('price', models.PositiveIntegerField(verbose_name='가격(원)')),
                ('credit_count', models.PositiveIntegerField(verbose_name='크레딧 개수')),
                ('period', models.PositiveIntegerField(verbose_name='사용기간(일)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(verbose_name='크레딧 개수')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('period', models.PositiveIntegerField(verbose_name='사용기간(일)')),
                ('is_expired', models.BooleanField(default=False)),
                ('price_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.pricepolicy', verbose_name='정책')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
