# Generated by Django 4.1.1 on 2022-10-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='expired_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.credit', verbose_name='만료된 크레딧'),
        ),
        migrations.AddField(
            model_name='credit',
            name='message',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credit',
            name='price_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.pricepolicy', verbose_name='가격 정책'),
        ),
    ]
