# Generated by Django 4.1.1 on 2022-10-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_credit_expired_credit_credit_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='period',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='사용기간(일)'),
        ),
    ]
