# Generated by Django 4.1.1 on 2022-10-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_initial'),
        ('credit', '0006_alter_credit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='lesson.reservation', verbose_name='예약'),
        ),
    ]
