# Generated by Django 4.1.1 on 2022-10-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_alter_credit_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedCredit',
            fields=[
                ('credit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='credit.credit')),
            ],
            options={
                'abstract': False,
            },
            bases=('credit.credit',),
        ),
        migrations.AddField(
            model_name='credit',
            name='remaining_count',
            field=models.IntegerField(default=0, verbose_name='남은 크레딧 개수'),
            preserve_default=False,
        ),
    ]
