# Generated by Django 4.1.1 on 2022-10-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0011_usecredit_credit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='remaining_count',
        ),
        migrations.AddField(
            model_name='credit',
            name='purchased_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_credits', to='credit.credit', verbose_name='구매된 크레딧'),
        ),
    ]
