# Generated by Django 4.1.1 on 2022-10-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0012_remove_credit_remaining_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='purchased_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_credits', to='credit.purchasecredit', verbose_name='구매된 크레딧'),
        ),
    ]
