# Generated by Django 4.1.1 on 2022-10-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0013_alter_credit_purchased_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundCredit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('credit.credit',),
        ),
        migrations.AlterField(
            model_name='credit',
            name='type',
            field=models.CharField(choices=[('구매', '구매한 크레딧'), ('사용', '사용한 크레딧'), ('만료', '만료된 크레딧'), ('환불', '환불된 크레딧')], default='구매', max_length=8, verbose_name='크레딧 종류'),
        ),
    ]
