# Generated by Django 4.1.1 on 2022-10-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('예약', '예약'), ('취소', '취소')], default='예약', max_length=8, verbose_name='예약/취소'),
        ),
    ]
