# Generated by Django 4.1.1 on 2022-10-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_reservation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='canceled_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.reservation', verbose_name='취소된 예약'),
        ),
    ]
