# Generated by Django 4.1.1 on 2022-10-02 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_reservation_canceled_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='canceled_reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancel_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.reservation', verbose_name='취소한 예약'),
        ),
    ]
